URL_SERVICE = " https://cnt-2a1ca150-38c1-4158-b121-cf0434366ff8.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"